import Aside from './board';
import {MutableRefObject, useReducer, useRef, useState} from "react";
import {DataSet, Filter as FilterType} from "./types";
import {AggContext, AggType} from "./AggTypes";

const get = {
    "fields": {
        "RiskFactorType": [
            "Subordinate",
            "SeniorSecured",
            "Junior",
            "NonSenior",
            "Unrated",
            "EqSpot",
            "Yield",
            "CDS",
            "SeniorUnsecured",
            "Bond",
            "Inflation",
            "Equity",
            null,
            "XCCY",
            "EqRepo",
            "Covered",
            "Senior"
        ],
        "CreditQuality": [
            "AA",
            "CCC",
            "Aaa",
            "BB",
            "B",
            null
        ],
        "CoveredBondReducedWeight": [
            "TRUE",
            null
        ],
        "Country": [
            "China",
            "SA",
            null,
            "France",
            "UK"
        ],
        "GirrVegaUnderlyingMaturity": [
            "Inflation",
            null,
            "XCCY",
            "1Y",
            "0.5Y"
        ],
        "RiskClass": [
            "Commodity",
            "FX",
            "Equity",
            "CSR_Sec_nonCTP",
            "CSR_nonSec",
            "DRC_NonSec",
            "DRC_SecNonCTP",
            "GIRR",
            "CSR_Sec_CTP",
            null
        ],
        "BucketBCBS": [
            "GBPEUR",
            "2",
            "Local Governments&Municipalities",
            "19",
            "17",
            "ABCP Asia",
            "1",
            "AED",
            "7",
            "16",
            "THBUSD",
            "Credit Cards Asia",
            "11",
            "GBP",
            "25",
            "13",
            "18",
            "10",
            "Auto Loans/Leases Asia",
            "5",
            "BRLUSD",
            "9",
            "Corporates Asia",
            "AUD",
            "EUR",
            "AZNUSD",
            "EURUSD",
            "RMBS Asia",
            "Corporates",
            "Sovereigns",
            "JPYEUR",
            "GBPUSD",
            null,
            "8"
        ],
        "Notional": [
            null
        ],
        "Sector": [
            null
        ],
        "Tranche": [
            "B_1",
            null,
            "B_222",
            "A_1",
            "AA_1",
            "B_2"
        ],
        "Group": [
            "Ultima",
            null
        ],
        "RiskFactor": [
            null,
            "6M_Libor",
            "Gold",
            "THOUSD",
            "GAS",
            "Samsung",
            "APPL",
            "SP500",
            "WTI",
            "Coal",
            "bbbb",
            "Acid",
            "GAZ",
            "GG",
            "Shell",
            "yyyy",
            "TEST",
            "Brent",
            "X_Y_AA",
            "Silver",
            "GBPEUR",
            "Urainum",
            "Steel",
            "XXX",
            "EURUSD",
            "Urals",
            "GBPUSD_xccy",
            "aaaa",
            "AED",
            "CCC",
            "ZZZ",
            "X_Y_B",
            "OIL",
            "GOOG",
            "JPYEUR",
            "GBPUSD_inf",
            "SHELL",
            "Infl101",
            "GBP",
            "xxxx",
            "MVP",
            "JohnLewis",
            "BETONIUM",
            "x_x_A",
            "DowJones",
            "AZNUSD",
            "3M_Libor",
            "YYY",
            "XAU",
            "BRLUSD",
            "ABC",
            "LG",
            "Rocks",
            "YYYYY",
            "GBPUSD",
            "UK Governemnt"
        ],
        "CommodityLocation": [
            "China",
            "London",
            "NY",
            null
        ],
        "LegalEntity": [
            null,
            "UK",
            "Asia",
            "BRICS",
            "EMEA"
        ],
        "MaturityDate": [
            null,
            "13/02/2023",
            "30/06/2023"
        ],
        "COB": [
            null,
            "22/07/2022"
        ],
        "Product": [
            "IRSwap",
            "FRA",
            "Forward",
            "FXOption",
            null,
            "Bond",
            "EqSpot",
            "TarfBoWo",
            "EQOption",
            "EQ_FRA",
            "Swaption",
            "CDS"
        ],
        "Desk": [
            "FXOptions",
            null,
            "RatesEM",
            "FXCash",
            "Rates"
        ],
        "SensitivityCcy": [
            "USD",
            "EUR"
        ],
        "BucketCRR2": [
            "16",
            "ABCP Asia",
            "13",
            "AUD",
            "9",
            null,
            "JPYEUR",
            "AED",
            "THBUSD",
            "10",
            "Credit Cards Asia",
            "EURUSD",
            "Corporates Asia",
            "2",
            "Local Governments&Municipalities",
            "BRLUSD",
            "Sovereigns",
            "7",
            "GBPUSD",
            "EUR",
            "Corporates",
            "1",
            "5",
            "GBPEUR",
            "8",
            "11",
            "GBP",
            "Auto Loans/Leases Asia",
            "18",
            "25",
            "19",
            "AZNUSD",
            "17",
            "RMBS Asia"
        ],
        "RiskCategory": [
            "DRC",
            "Vega",
            "Delta",
            null
        ]
    },
    "measures": {
        "FX_VegaCharge_MAX": "first",
        "CSR_nonSec_VegaCharge_Low": "first",
        "CSR_Sec_nonCTP_VegaCharge_High": "first",
        "SensitivitySpot": null,
        "CSR_Sec_nonCTP_Curvature_Kb_Medium": "first",
        "CSR_nonSec_CurvatureDelta_Weighted": null,
        "FX_VegaSens_Weighted": null,
        "GIRR_VegaCharge_Low": "first",
        "EQ_Curvature_KbPlus_Low": "first",
        "CSR_secCTP_DeltaKb_High": "first",
        "FX_CVRup": null,
        "CSR_Sec_nonCTP_Curvature_KbPlus_High": "first",
        "CSR_Sec_nonCTP_VegaKb_Low": "first",
        "CSR_secCTP_VegaKb_High": "first",
        "CSR_Sec_nonCTP_Curvature_Sb_Low": "first",
        "EQ_VegaKb_Medium": "first",
        "FX_TotalCharge_High": "first",
        "SBM_Charge": "first",
        "Sensitivity_2Y": null,
        "Commodity_Curvature_KbMinus_Low": "first",
        "EQ_CVRdown": null,
        "EQ_DeltaCharge_MAX": "first",
        "FX_VegaSens": null,
        "CSR_nonSec_Curvature_KbPlus_High": "first",
        "FX_Curvature_KbMinus": "first",
        "DRC_SecNonCTP_NetShortJTD_Weighted": null,
        "SBM_Charge_High": "first",
        "FX_CurvatureCharge_High": "first",
        "CSR_Sec_nonCTP_VegaSens": null,
        "CSR_nonSec_DeltaCharge_High": "first",
        "CSR_secCTP_DeltaCharge_MAX": "first",
        "Commodity_Curvature_KbMinus_High": "first",
        "Commodity_Curvature_KbPlus_Medium": "first",
        "Commodity_VegaKb_High": "first",
        "DRC_NonSec_NetAbsShortJTD_Weighted": "first",
        "CSR_secCTP_VegaSb": "first",
        "GIRR_DeltaSb": "first",
        "EQ_Curvature_Sb_Low": "first",
        "CSR_nonSec_VegaSens_Weighted": null,
        "CSR_secCTP_PnLup": null,
        "Commodity_VegaSb": "first",
        "GIRR_DeltaCharge_Medium": "first",
        "EQ_CVRup": null,
        "GIRR_VegaSens": null,
        "CSR_nonSec_DeltaSb": "first",
        "CSR_Sec_nonCTP_VegaSb": "first",
        "DRC_NonSec_NetLongJTD": "first",
        "FX_VegaCharge_High": "first",
        "FX_Curvature_Kb": "first",
        "FX_VegaKb_Medium": "first",
        "SBM_Charge_Medium": "first",
        "Sensitivity_025Y": null,
        "Commodity_DeltaCharge_Medium": "first",
        "CSR_nonSec_VegaKb_Low": "first",
        "FX_VegaCharge_Low": "first",
        "Commodity_Curvature_KbPlus_Low": "first",
        "DRC_NonSec_NetShortJTD": "first",
        "CSR_nonSec_DeltaCharge_Low": "first",
        "CSR_Sec_nonCTP_CurvatureDelta_Weighted": null,
        "GIRR_VegaKb_Medium": "first",
        "SBM_Charge_Low": "first",
        "Commodity_Curvature_KbMinus_Medium": "first",
        "CSR_secCTP_Curvature_Kb_High": "first",
        "CSR_secCTP_DeltaSb": "first",
        "CSR_Sec_nonCTP_VegaKb_Medium": "first",
        "EQ_CurvatureCharge_High": "first",
        "CSR_nonSec_CurvatureCharge_Low": "first",
        "EQ_VegaCharge_MAX": "first",
        "CSR_secCTP_CurvatureDelta_Weighted": null,
        "GIRR_TotalCharge_Low": null,
        "CSR_secCTP_DeltaKb_Low": "first",
        "RiskWeights": "first",
        "CSR_nonSec_DeltaSens_Weighted": null,
        "EQ_Curvature_KbPlus_Medium": "first",
        "DRC_SecNonCTP_HBR": null,
        "CSR_nonSec_Curvature_Sb_Low": "first",
        "Sensitivity_3Y": null,
        "GIRR_Curvature_KbPlus": "first",
        "CSR_nonSec_VegaCharge_High": "first",
        "CSR_nonSec_DeltaKb_Low": "first",
        "DRC_NonSec_GrossJTD_Scaled": null,
        "Commodity_PnLup": null,
        "EQ_VegaCharge_High": "first",
        "CSR_secCTP_Curvature_KbMinus_Low": "first",
        "Commodity_VegaCharge_Low": "first",
        "CSR_nonSec_VegaCharge_MAX": "first",
        "Commodity_Curvature_Kb_Medium": "first",
        "GIRR_DeltaCharge_MAX": "first",
        "CSR_secCTP_CVRup": null,
        "CSR_secCTP_DeltaKb_Medium": "first",
        "CSR_nonSec_VegaKb_High": "first",
        "CSR_secCTP_CurvatureCharge_High": "first",
        "CSR_Sec_nonCTP_VegaKb_High": "first",
        "GIRR_Curvature_Sb": "first",
        "GIRR_VegaKb_High": "first",
        "CSR_secCTP_Curvature_KbPlus_Low": "first",
        "EQ_DeltaKb_Low": "first",
        "DRC_SecNonCTP_GrossJTD_Scaled": null,
        "CSR_secCTP_DeltaCharge_Low": "first",
        "GIRR_VegaKb_Low": "first",
        "EQ_DeltaCharge_Medium": "first",
        "CSR_secCTP_VegaKb_Medium": "first",
        "CSR_secCTP_TotalCharge_High": "first",
        "CSR_Sec_nonCTP_DeltaSens_Weighted": null,
        "CSR_nonSec_Curvature_Kb_Medium": "first",
        "CSR_Sec_nonCTP_VegaCharge_MAX": "first",
        "CSR_secCTP_VegaCharge_Low": "first",
        "GIRR_DeltaCharge_High": "first",
        "CSR_secCTP_Curvature_KbMinus_Medium": "first",
        "Commodity_DeltaKb_Low": "first",
        "Commodity_VegaSens_Weighted": null,
        "FX_CurvatureCharge_Medium": "first",
        "GIRR_TotalCharge_High": "first",
        "CSR_secCTP_DeltaSens": null,
        "CSR_secCTP_Curvature_Kb_Low": "first",
        "GIRR_VegaSens_Weighted": null,
        "FX_CurvatureCharge_Low": "first",
        "Commodity_VegaKb_Medium": "first",
        "CSR_Sec_nonCTP_VegaSens_Weighted": null,
        "FX_CurvatureDelta_Weighted": null,
        "CSR_nonSec_TotalCharge_Low": "first",
        "Commodity_VegaCharge_High": "first",
        "EQ_TotalCharge_High": "first",
        "EQ_VegaSb": "first",
        "CSR_nonSec_VegaSb": "first",
        "DRC_SecNonCTP_NetLongJTD": null,
        "FX_TotalCharge_Medium": "first",
        "CSR_secCTP_VegaSens_Weighted": null,
        "GrossJTD": null,
        "CSR_nonSec_CurvatureCharge_MAX": "first",
        "FX_VegaKb_Low": "first",
        "Commodity_DeltaCharge_High": "first",
        "EQ_VegaSens": null,
        "EQ_CurvatureDelta_Weighted": null,
        "Commodity_DeltaKb_High": "first",
        "GIRR_PnLup": null,
        "CSR_nonSec_Curvature_Kb_Low": "first",
        "CSR_Sec_nonCTP_CurvatureCharge_Low": "first",
        "CSR_secCTP_VegaCharge_Medium": "first",
        "CSR_nonSec_VegaCharge_Medium": "first",
        "GIRR_CurvatureDelta_Weighted": null,
        "EQ_Curvature_Sb_Medium": "first",
        "CSR_secCTP_Curvature_KbPlus_Medium": "first",
        "Commodity_VegaKb_Low": "first",
        "CSR_nonSec_Curvature_Kb_High": "first",
        "EQ_Curvature_KbMinus_Medium": "first",
        "Commodity_Curvature_KbPlus_High": "first",
        "Commodity_TotalCharge_Low": "first",
        "FX_DeltaCharge_Medium": "first",
        "CSR_Sec_nonCTP_DeltaSb": null,
        "CSR_nonSec_DeltaKb_High": "first",
        "Commodity_DeltaCharge_Low": "first",
        "CSR_secCTP_VegaCharge_High": "first",
        "Commodity_DeltaSb": "first",
        "CSR_Sec_nonCTP_Curvature_Kb_High": "first",
        "FX_PnLup": null,
        "EQ_VegaKb_Low": "first",
        "EQ_CurvatureCharge_Low": "first",
        "Commodity_CurvatureDelta": null,
        "Commodity_CVRup": null,
        "GIRR_DeltaKb_High": "first",
        "GIRR_Curvature_Kb": "first",
        "CSR_nonSec_DeltaCharge_MAX": "first",
        "EQ_DeltaKb_High": "first",
        "GIRR_CurvatureCharge_Medium": "first",
        "CSR_nonSec_PnLup": null,
        "DRC_NonSec_NetLongJTD_Weighted": "first",
        "FX_DeltaSens_Weighted": null,
        "CSR_Sec_nonCTP_Curvature_Sb_High": "first",
        "GIRR_VegaCharge_MAX": "first",
        "Commodity_CurvatureCharge_Low": "first",
        "CSR_Sec_nonCTP_VegaCharge_Medium": "first",
        "DRC_NonSec_CapitalCharge": "first",
        "FX_CurvatureCharge_MAX": "first",
        "GIRR_CurvatureDelta": null,
        "Commodity_TotalCharge_Medium": "first",
        "CSR_Sec_nonCTP_VegaCharge_Low": "first",
        "CSR_nonSec_CVRdown": null,
        "CSR_Sec_nonCTP_DeltaSens": null,
        "CSR_Sec_nonCTP_Curvature_Kb_Low": "first",
        "FX_DeltaCharge_Low": "first",
        "EQ_CurvatureDelta": null,
        "CSR_Sec_nonCTP_CurvatureCharge_MAX": "first",
        "CSR_nonSec_Curvature_KbPlus_Low": "first",
        "CSR_Sec_nonCTP_Curvature_KbPlus_Medium": "first",
        "Sensitivity_15Y": null,
        "CSR_Sec_nonCTP_CVRup": null,
        "EQ_PnLup": null,
        "Commodity_CurvatureCharge_High": "first",
        "CSR_Sec_nonCTP_CVRdown": null,
        "Commodity_DeltaSens": null,
        "GIRR_Curvature_KbMinus": "first",
        "CSR_nonSec_Curvature_KbMinus_High": "first",
        "Sensitivity_5Y": null,
        "CSR_nonSec_Curvature_KbPlus_Medium": "first",
        "GIRR_DeltaSens_Weighted": null,
        "FX_DeltaSens": null,
        "Commodity_VegaCharge_Medium": "first",
        "EQ_VegaSens_Weighted": null,
        "FX_CurvatureDelta": null,
        "EQ_Curvature_Kb_High": "first",
        "CSR_Sec_nonCTP_Curvature_Sb_Medium": "first",
        "EQ_CurvatureCharge_Medium": "first",
        "PnL_Down": null,
        "CSR_Sec_nonCTP_Curvature_KbMinus_Low": "first",
        "CSR_Sec_nonCTP_DeltaCharge_Low": null,
        "EQ_Curvature_KbMinus_Low": "first",
        "CSR_nonSec_PnLdown": null,
        "CSR_secCTP_PnLdown": null,
        "CSR_Sec_nonCTP_CurvatureCharge_Medium": "first",
        "EQ_VegaCharge_Low": "first",
        "GIRR_CVRup": null,
        "CSR_secCTP_DeltaCharge_Medium": "first",
        "FX_PnLdown": null,
        "CSR_Sec_nonCTP_DeltaCharge_MAX": null,
        "CSR_nonSec_CurvatureCharge_High": "first",
        "CSR_Sec_nonCTP_CurvatureDelta": null,
        "GIRR_PnLdown": null,
        "EQ_Curvature_Kb_Low": "first",
        "Commodity_CurvatureDelta_Weighted": null,
        "CSR_Sec_nonCTP_Curvature_KbMinus_High": "first",
        "FX_DeltaCharge_High": "first",
        "CSR_Sec_nonCTP_DeltaKb_Low": null,
        "GIRR_DeltaKb_Medium": "first",
        "Sensitivity_05Y": null,
        "DRC_NonSec_GrossJTD": null,
        "CSR_secCTP_Curvature_Kb_Medium": "first",
        "CSR_Sec_nonCTP_PnLup": null,
        "Commodity_DeltaSens_Weighted": null,
        "Commodity_TotalCharge_MAX": "first",
        "FX_DeltaSb": "first",
        "Commodity_CurvatureCharge_Medium": "first",
        "EQ_TotalCharge_Medium": "first",
        "EQ_DeltaKb_Medium": "first",
        "GIRR_CVRdown": null,
        "Sensitivity_20Y": null,
        "GIRR_CurvatureCharge_High": "first",
        "Commodity_DeltaKb_Medium": "first",
        "CSR_Sec_nonCTP_DeltaCharge_High": null,
        "Commodity_TotalCharge_High": "first",
        "EQ_DeltaCharge_High": "first",
        "EQ_DeltaSens": null,
        "EQ_Curvature_Kb_Medium": "first",
        "CSR_nonSec_Curvature_Sb_Medium": "first",
        "CSR_secCTP_DeltaCharge_High": "first",
        "Commodity_PnLdown": null,
        "CSR_secCTP_VegaKb_Low": "first",
        "CSR_nonSec_CurvatureDelta": null,
        "CSR_Sec_nonCTP_DeltaKb_High": null,
        "FX_Curvature_KbPlus": "first",
        "GIRR_VegaCharge_Medium": "first",
        "CSR_Sec_nonCTP_CurvatureCharge_High": "first",
        "CSR_secCTP_Curvature_KbMinus_High": "first",
        "CSR_secCTP_CurvatureCharge_Low": "first",
        "EQ_DeltaSens_Weighted": null,
        "FX_DeltaKb": "first",
        "CSR_nonSec_CurvatureCharge_Medium": "first",
        "Sensitivity_1Y": null,
        "EQ_Curvature_Sb_High": "first",
        "CSR_nonSec_DeltaSens": null,
        "GIRR_VegaCharge_High": "first",
        "Commodity_Curvature_Sb_High": "first",
        "FX_TotalCharge_Low": "first",
        "FX_Curvature_Sb": "first",
        "CSR_secCTP_TotalCharge_Medium": "first",
        "CSR_Sec_nonCTP_TotalCharge_Medium": "first",
        "CSR_secCTP_Curvature_Sb_High": "first",
        "FX_VegaCharge_Medium": "first",
        "CSR_nonSec_CVRup": null,
        "DRC_NonSec_HBR": "first",
        "CSR_nonSec_VegaSens": null,
        "FX_VegaKb_High": "first",
        "EQ_CurvatureCharge_MAX": "first",
        "GIRR_CurvatureCharge_Low": "first",
        "FX_VegaSb": "first",
        "EQ_Curvature_KbMinus_High": "first",
        "Commodity_Curvature_Sb_Low": "first",
        "Sensitivity_30Y": null,
        "CSR_secCTP_Curvature_Sb_Low": "first",
        "GIRR_DeltaSens": null,
        "CSR_nonSec_VegaKb_Medium": "first",
        "CSR_Sec_nonCTP_DeltaKb_Medium": null,
        "CSR_Sec_nonCTP_Curvature_KbPlus_Low": "first",
        "CSR_secCTP_TotalCharge_Low": "first",
        "CSR_secCTP_Curvature_Sb_Medium": "first",
        "Commodity_VegaSens": null,
        "Commodity_Curvature_Kb_High": "first",
        "CSR_secCTP_CurvatureCharge_Medium": "first",
        "EQ_VegaCharge_Medium": "first",
        "Commodity_Curvature_Sb_Medium": "first",
        "GIRR_VegaSb": "first",
        "EQ_DeltaSb": "first",
        "FX_CVRdown": null,
        "FX_DeltaCharge_MAX": "first",
        "Commodity_Curvature_Kb_Low": "first",
        "CSR_secCTP_VegaCharge_MAX": "first",
        "Commodity_VegaCharge_MAX": "first",
        "GIRR_CurvatureCharge_MAX": "first",
        "EQ_DeltaCharge_Low": "first",
        "CSR_nonSec_Curvature_KbMinus_Low": "first",
        "CSR_secCTP_Curvature_KbPlus_High": "first",
        "Commodity_CurvatureCharge_MAX": "first",
        "Sensitivity_10Y": null,
        "DRC_SecNonCTP_CapitalCharge": null,
        "EQ_PnLdown": null,
        "DRC_SecNonCTP_GrossJTD": null,
        "CSR_secCTP_CurvatureCharge_MAX": "first",
        "EQ_Curvature_KbPlus_High": "first",
        "CSR_nonSec_Curvature_Sb_High": "first",
        "Commodity_DeltaCharge_MAX": "first",
        "CSR_secCTP_VegaSens": null,
        "GIRR_DeltaCharge_Low": "first",
        "CSR_Sec_nonCTP_PnLdown": null,
        "EQ_TotalCharge_Low": "first",
        "CSR_nonSec_TotalCharge_High": "first",
        "GIRR_TotalCharge_Medium": null,
        "GIRR_DeltaKb_Low": "first",
        "CSR_nonSec_TotalCharge_Medium": "first",
        "CSR_secCTP_CVRdown": null,
        "CSR_nonSec_DeltaCharge_Medium": "first",
        "CSR_Sec_nonCTP_TotalCharge_High": "first",
        "DRC_SecNonCTP_NetLongJTD_Weighted": null,
        "CSR_secCTP_DeltaSens_Weighted": null,
        "CSR_Sec_nonCTP_DeltaCharge_Medium": null,
        "EQ_VegaKb_High": "first",
        "CSR_Sec_nonCTP_TotalCharge_Low": "first",
        "CSR_nonSec_Curvature_KbMinus_Medium": "first",
        "Commodity_CVRdown": null,
        "PnL_Up": null,
        "CSR_nonSec_DeltaKb_Medium": "first",
        "DRC_SecNonCTP_NetShortJTD": null,
        "CSR_Sec_nonCTP_Curvature_KbMinus_Medium": "first",
        "CSR_secCTP_CurvatureDelta": null
    }
}

function aggTypesReducer(state: { [p: string]: AggType }, action: any) {
    return {
        ...state,
        [action.field]: action.agg
    }
}

export const Initial = () => {
    const dataSet = useState<DataSet>(() => ({
        fields: Object.keys(get.fields),
        measures: Object.keys(get.measures),
        groupby: [],
        overwrites: [],
        measuresSelected: [],
    }))

    const filters: MutableRefObject<{ [p: number]: { [p: number]: FilterType } }> = useRef({})

    const [aggData, aggDataUpdater] = useReducer(aggTypesReducer, {})

    const run = () => {
        const data = dataSet[0]
        console.log({
            filters: Object.values(filters.current),
            overwrites: data.overwrites,
            groupby: data.groupby,
            measures: data.measuresSelected
        })
    }

    return (
        <div>
            <AggContext.Provider value={{
                data: aggData,
                updater: aggDataUpdater
            }}>
                <Aside dataSet={dataSet} filters={filters} />
            </AggContext.Provider>
            <button onClick={run}>run</button>
        </div>
    )
}

export { Aside }

export default Initial
